/*
* generated by Xtext
*/
package org.eclipse.xtext.mongobeans.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.mongobeans.services.MongoBeansGrammarAccess;

public class MongoBeansParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MongoBeansGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.mongobeans.parser.antlr.internal.InternalMongoBeansParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.mongobeans.parser.antlr.internal.InternalMongoBeansParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MongoFile";
	}
	
	public MongoBeansGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MongoBeansGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
