/*
* generated by Xtext
*/
package org.eclipse.xtext.mongobeans.ui.contentassist;

import org.eclipse.xtext.mongobeans.ui.contentassist.AbstractMongoBeansProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MongoBeansProposalProvider extends AbstractMongoBeansProposalProvider {

}
