/*
* generated by Xtext
*/
package org.eclipse.xtext.mongobeans;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MongoBeansUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.xtext.mongobeans.ui.internal.MongoBeansActivator.getInstance().getInjector("org.eclipse.xtext.mongobeans.MongoBeans");
	}
	
}
