/*
 * generated by Xtext
 */
package org.eclipse.xtext.mongobeans.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MongoBeansUiModule extends org.eclipse.xtext.mongobeans.ui.AbstractMongoBeansUiModule {
	public MongoBeansUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
